language: ruby
rvm:
  - "1.9.3"
  - "1.9.2"
env:
  - DB=sqlite
script:
  - RAILS_ENV=development bundle exec rake --trace db:migrate
  - RAILS_ENV=development bundle exec rake db:test:prepare
  - RAILS_ENV=development bundle exec rake rspec spec
